[theme]

# Primary accent for interactive elements
primaryColor = '#333333'

# Background color for the main content area
backgroundColor = '#ff9bb3'

# Background color for sidebar and most interactive widgets
secondaryBackgroundColor = '#FFE082'

# Color used for almost all text
textColor = '#333333'

# Font family for all text in the app, except code blocks
# Accepted values (serif | sans serif | monospace) 
# Default: "sans serif"
# font = "sans serif"
